### ISSUE TITLE
Stock market 

### ISSUE THREAD

**Issue by tipptapp** [AlexanderJarvheden/Project-Bank-Application#2]

**Comment by AlexanderJarvheden** [comment]
Logos are needed, tabs need to be stationary and visible at all times, not necessary to scroll all the way to the bottom of Stock Market to find them

**Comment by AlexanderJarvheden** [comment]
Perhaps allow user to transfer money from savings accounts to investment account/portfolio balance by using the transfer functions displayed for the other transfers, need to be specified though since this money can be moved immediately and not in relation to the time of the day
