### ISSUE TITLE
Loan plattform requirements

### ISSUE THREAD

**Issue by AlexanderJarvheden** [AlexanderJarvheden/Project-Bank-Application#21]
Provides an overview of the users total loans and the amortized amount.

Offers a list with current interest rates depending on the users risk status.

The risk formulas are as following messages:

**Comment by AlexanderJarvheden** [comment]
Low risk: user has more than the loaned amount in its savings, eg total savings = 1 million, whilst loan is less than 1 million meaning that the user actually can pay off the loan. Interest rates might be the Swedish central bank's current rate + 1.5%

**Comment by AlexanderJarvheden** [comment]
Low medium risk: user has 75% of the loan in savings. Interest rate should be SCB rate + 2.5%

**Comment by AlexanderJarvheden** [comment]
Medium risk: user has 50 % of the loan in savings: Interest rate should be SCB rate + 3.5%

**Comment by AlexanderJarvheden** [comment]
Medium high risk: user has 30% of the loan in savings: Interest rate should be SCB + 5%

**Comment by AlexanderJarvheden** [comment]
High risk: User has 15% of the loan in savings: Interest rate should be SCB + 8%

**Comment by AlexanderJarvheden** [comment]
Extremely high risk: User has less than 15% of the loan in savings: Interest rate should not exist since this is way too big risk for the bank

**Comment by tipptapp** [comment]
I have provided an interface for the loanplatform, where you can make payments and create new loans. Problems with how the users are saved in the database needs to be updated in order for it to work (create new loan).
