### ISSUE TITLE
Newly created user works as a "one time entry"

### ISSUE THREAD

**Issue by AlexanderJarvheden** [AlexanderJarvheden/Project-Bank-Application#23]
![image](https://user-images.githubusercontent.com/131161901/236700121-6b416041-9026-4479-ba90-5daa9b6eab9a.png)

The commented one is the one we want so that when the "new user" is clicked the create new user fields show up, but the user that then is created is not actually created since it cannot sign in. 

However, with the second row in the code the user actually is created and manages to sign in, only once though because when he signs out the user cannot sign back in since its not been added in the banks users map

**Comment by AlexanderJarvheden** [comment]
This is found in the Interface/app/index.js

**Comment by zizo2001** [comment]
Closed
